# Generated by Django 4.1.7 on 2023-04-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityTrekk', '0002_post_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
