# Generated by Django 4.1.7 on 2023-04-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityTrekk', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
