# Generated by Django 4.1.7 on 2023-04-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityTrekk', '0008_mensaje'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='principal_description',
            new_name='principal_subtitle',
        ),
    ]
